# Generated by Django 5.1.4 on 2026-04-24 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('exercise_type', models.CharField(choices=[('cardio', 'Cardio'), ('strength', 'Strength'), ('hiit', 'HIIT'), ('yoga', 'Yoga'), ('sports', 'Sports'), ('walking', 'Walking'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('flexibility', 'Flexibility'), ('other', 'Other')], default='other', max_length=20)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('intensity', models.CharField(default='moderate', max_length=20)),
                ('calories_burned', models.FloatField(default=0)),
                ('estimated', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_logs', to='chat.chatsession')),
                ('source_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
