# Generated by Django 5.1.4 on 2026-05-19 02:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciselog',
            name='occurred_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
