# Generated by Django 5.1.4 on 2026-04-24 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(default=30)),
                ('gender', models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino'), ('other', 'Otro')], default='other', max_length=10)),
                ('weight_kg', models.FloatField(default=70)),
                ('height_cm', models.FloatField(default=170)),
                ('goal', models.CharField(choices=[('weight_loss', 'Perdida de peso'), ('muscle_gain', 'Aumento de masa muscular'), ('body_recomposition', 'Recomposicion corporal'), ('maintenance', 'Mantenimiento'), ('athletic_performance', 'Rendimiento deportivo')], default='maintenance', max_length=30)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentario'), ('light', 'Ligero'), ('moderate', 'Moderado'), ('active', 'Activo'), ('very_active', 'Muy activo')], default='moderate', max_length=20)),
                ('timezone', models.CharField(default='America/Bogota', max_length=64)),
                ('daily_calorie_target', models.IntegerField(default=2100)),
                ('protein_target_g', models.IntegerField(default=130)),
                ('carbs_target_g', models.IntegerField(default=230)),
                ('fat_target_g', models.IntegerField(default=70)),
                ('streak_days', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
