# Generated by Django 5.1.4 on 2026-06-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrainingExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_text", models.TextField()),
                ("intent_label", models.CharField(max_length=50)),
                ("confidence", models.FloatField(default=0.0)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("predicted", "Predicted"),
                            ("confirmed", "Confirmed"),
                        ],
                        default="predicted",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["is_active", "source"],
                        name="ai_training_is_acti_1df7ec_idx",
                    )
                ],
            },
        ),
    ]
