# Generated by Django 5.1.4 on 2026-05-19 02:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meallog',
            name='nutrition_confidence',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='meallog',
            name='nutrition_source',
            field=models.CharField(choices=[('usda', 'USDA'), ('local', 'Local DB'), ('llm', 'LLM Estimate')], default='llm', max_length=10),
        ),
        migrations.AddField(
            model_name='meallog',
            name='occurred_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='meallog',
            name='usda_fdc_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
